// sites/odroe.devold/components/navigation.vue
<template>
  <nav>
    <template v-for="link in navigation">
      <Menu as="div" class="relative" v-if="link.children?.length">
        <MenuButton
          class="nav-link flex items-center gap-1 group"
          :aria-selected="link.active"
        >
          {{ link.label }}
          <ChevronDownIcon
            class="size-4 transition-all group-aria-expanded:rotate-180"
          />
        </MenuButton>

        <transition
          enter-active-class="transition duration-100 ease-out"
          enter-from-class="transform scale-95 opacity-0"
          enter-to-class="transform scale-100 opacity-100"
          leave-active-class="transition duration-75 ease-in"
          leave-from-class="transform scale-100 opacity-100"
          leave-to-class="transform scale-95 opacity-0"
        >
          <MenuItems
            class="absolute mt-4 w-64 right-0 origin-top-right divide-y divide-gray-100 rounded-md bg-white ring-1 ring-black/5 focus:outline-none"
          >
            <div class="p-2 grid grid-cols-1 gap-2">
              <MenuItem v-for="child in link.children">
                <NuxtLink
                  :to="child.to"
                  :aria-selected="child.active"
                  class="p-2 pt-1 rounded flex gap-2 bg-transparent hover:bg-gray-100/75 aria-selected:bg-gray-100/75 transition-all"
                >
                  <component :is="child.icon" class="size-4 flex-none mt-1" />
                  <div class="flex-1 grow">
                    <h3 class="font-semibold text-sm/6 text-black">
                      {{ child.label }}
                    </h3>
                    <div class="line-clamp-2 text-sm/4 text-gray-600/75">
                      {{ child.desc }}
                    </div>
                  </div>
                </NuxtLink>
              </MenuItem>
            </div>
          </MenuItems>
        </transition>
      </Menu>

      <NuxtLink
        v-if="link.to"
        :to="link.to"
        :aria-selected="link.active"
        class="nav-link"
      >
        {{ link.label }}
      </NuxtLink>
    </template>
  </nav>
</template>

<script setup lang="ts">
import {
  Menu,
  MenuButton,
  MenuItem,
  MenuItems,
  provideUseId,
} from '@headlessui/vue';
import ChevronDownIcon from '@heroicons/vue/24/solid/ChevronDownIcon';

const navigation = useNavigation();

provideUseId(() => useId());
</script>

<style scoped>
.nav-link {
  @apply text-sm/6 font-semibold text-black dark:text-white relative before:absolute before:-left-4 before:-right-4 before:-top-1 before:-bottom-1 before:rounded-full before:bg-transparent before:hover:bg-black/5 aria-selected:before:bg-black/5 before:-z-10 dark:before:hover:bg-white/15 aria-selected:dark:before:bg-white/15;
}
</style>

// sites/odroe.dev/app/(app)/_navigation.tsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import {
  Popover,
  PopoverButton,
  PopoverGroup,
  PopoverPanel,
  Transition,
  type PopoverGroupProps,
} from '@headlessui/react';
import { ChevronDownIcon } from '@heroicons/react/16/solid';
import classes from './nav.module.css';

type NavLink = { label: string; href: string };
type DropdownLinkChild = NavLink & {
  desc: string;
};
type DropdownLink = NavLink & { children: DropdownLinkChild[] };

const navigation: (NavLink | DropdownLink)[] = [
  { label: 'Docs', href: '/docs' },
  { label: 'UI', href: '/ui' },
  { label: 'Templates', href: '/templates' },
  { label: 'Showcase', href: '/showcase' },
  {
    label: 'Enterprise',
    href: '/enterprise',
    children: [
      {
        label: 'Support',
        href: '/enterprise/support',
        desc: 'Get help with Odroe directly from the team that creates it.',
      },
      {
        label: 'Sponsors',
        href: '/enterprise/sponsors',
        desc: 'Become a sponsor and get your logo on our README on GitHub with a link to your site.',
      },
    ],
  },
  { label: 'Blog', href: '/blog' },
];

const DropdownNavItem = ({ label, href, desc }: DropdownLinkChild) => {
  const pathname = usePathname();

  return (
    <a
      className="block rounded-lg py-2 px-3 transition dark:hover:bg-white/5 hover:bg-gray-500/5"
      href={href}
      aria-selected={pathname.startsWith(href)}
    >
      <p className="font-semibold dark:text-white text-black">{label}</p>
      <p className="dark:text-white/50 text-black/50 line-clamp-2">{desc}</p>
    </a>
  );
};

const DropdownNav = ({ label, href, children }: DropdownLink) => {
  const pathname = usePathname();

  return (
    <Popover className="relative">
      <PopoverButton
        className={`${classes.nav_link} group focus:outline-none flex items-center cursor-pointer`}
        aria-selected={pathname.startsWith(href)}
      >
        {label}
        <ChevronDownIcon className="size-4 transition-all group-aria-expanded:rotate-180" />
      </PopoverButton>

      <Transition
        enter="transition ease-out duration-200"
        enterFrom="opacity-0 translate-y-1"
        enterTo="opacity-100 translate-y-0"
        leave="transition ease-in duration-150"
        leaveFrom="opacity-100 translate-y-0"
        leaveTo="opacity-0 translate-y-1"
      >
        <PopoverPanel
          anchor={{
            to: 'bottom',
            gap: 12,
          }}
          className="rounded-xl bg-white/5 text-sm/6 [--anchor-gap:var(--spacing-5)] shadow border dark:border-white/5 border-black/10"
        >
          <div className="p-3 max-w-80">
            {children.map((props) => (
              <DropdownNavItem key={props.href} {...props} />
            ))}
          </div>
        </PopoverPanel>
      </Transition>
    </Popover>
  );
};

const NavItem = (props: NavLink | DropdownLink) => {
  if ('children' in props && props.children.length) {
    return <DropdownNav {...props} />;
  }

  const { label, href } = props;
  const pathname = usePathname();

  return (
    <Link
      key={href}
      href={href}
      aria-selected={pathname.startsWith(href)}
      className={classes.nav_link}
    >
      {label}
    </Link>
  );
};

export const Navigation = (props: Omit<PopoverGroupProps<'nav'>, 'as'>) => (
  <PopoverGroup {...props} as="nav">
    {navigation.map((nav) => (
      <NavItem key={nav.href} {...nav} />
    ))}
  </PopoverGroup>
);
